# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3d6f11e95edd3b65fda4a8681022d240c107e7d6b5c7d6328ebe666d55fc3b940280babd33400e421a25ff48935e3fc9095b00fec3caeb8554872433a9b601b

test:
  secret_key_base: f49bca3ca6af1a77ad842d39cb508841979ab5e4cc8062d382c47f88ade28e96511a5cfea1f874cb80b2519dd9cd21ab148e52206b63cbbf4dbf9d8d6268e973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
